apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gai82uf51-go 
  janus-idp.io/tekton: gai82uf51-go
  backstage.io/kubernetes-id: gai82uf51-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gai82uf51-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  