apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gai82uf51-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gai82uf51-go 
  name: gai82uf51-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gai82uf51-go 
